# Generated by Django 3.2.9 on 2024-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20240206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='Link',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
